function [beta,k,M,phi,defl,defl_cant,ectop,es_T] = zone322(beta,L,b,h,alpha,E,epsilon_cr,beta_1,beta_2,beta_3,eta_1,eta_2,eta_3,xi,omega,eta_c,n,kappa,eta_s,rho_c,rho_t)
x=L/2;%location to find deflection along the beam
x2 = L;
k = real(((-1 + beta_1) .* (beta_1 - 2 .* beta + 1) .* eta_1 + xi .* omega .* (beta + omega) .* eta_c - (beta_1 - beta).^2 .* eta_2 - xi .* omega .* (beta + omega) - n .* (eta_s .* rho_t + rho_c) .* beta.^2 + (kappa .* n .* eta_s .* rho_t - kappa .* n .* rho_t - 2) .* beta + sqrt(beta.^2 .* (((eta_s .* beta - kappa .* (eta_s - 1)) .* rho_t + beta .* rho_c).^2 .* n.^2 + ((2 .* (xi .* alpha .* eta_c - eta_2 .* (alpha - 1)) .* eta_s .* beta.^2 + (((4 .* omega .* (eta_c - 1) .* alpha + (-2 .* kappa - 2 .* omega) .* eta_c + 2 .* omega) .* xi - 4 .* ((eta_1 - eta_2) .* beta_1 - eta_1 + 1) .* (alpha - 1)) .* eta_s + 2 .* xi .* kappa .* eta_c) .* beta + (2 .* omega .* (eta_c - 1) .* (alpha .* omega - kappa - omega) .* xi + 2 .* ((eta_1 - eta_2) .* beta_1.^2 - eta_1 + 1) .* (alpha - 1)) .* eta_s + 2 .* xi .* kappa .* omega .* (eta_c - 1)) .* rho_t - 2 .* ((eta_c .* (alpha - 1) .* xi - alpha .* eta_2) .* beta.^2 + (2 .* (eta_c - 1) .* (alpha - 1/2) .* omega .* xi - 2 .* ((eta_1 - eta_2) .* beta_1 - eta_1 + 1) .* alpha) .* beta + alpha .* (omega.^2 .* (eta_c - 1) .* xi + (eta_1 - eta_2) .* beta_1.^2 - eta_1 + 1)) .* rho_c) .* n - (-eta_2 .* eta_c .* beta.^2 - 2 .* eta_c .* ((eta_1 - eta_2) .* beta_1 - eta_1 + 1) .* beta + omega.^2 .* (eta_c - 1) .* xi + eta_c .* ((eta_1 - eta_2) .* beta_1.^2 - eta_1 + 1)) .* xi)) + 1) ./ ((-1 + beta_1) .* (beta_1 - 2 .* beta + 1) .* eta_1 + xi .* (beta + omega).^2 .* eta_c - (beta_1 - beta).^2 .* eta_2 + (-2 .* beta .* omega - omega.^2) .* xi - 2 .* beta + 1));

M = epsilon_cr * h^2 * ( ...
    ((-2 * xi * eta_c + 2 * eta_2) .* beta.^3 ...
    + ((3 * eta_1 - 3 * eta_2) * beta_1 - 3 * eta_1 + 3 + (-3 * eta_c + 3) * omega * xi) .* beta.^2 ...
    + (-eta_1 + eta_2) * beta_1.^3 + eta_1 - 1 + (eta_c - 1) * omega.^3 * xi) .* k.^3 ...
    + (((-6 * eta_s * rho_t - 6 * rho_c) * n - 6 * eta_2) .* beta.^3 ...
    + (6 * rho_t * kappa * (eta_s - 1) * n + (-9 * eta_1 + 9 * eta_2) * beta_1 + 9 * eta_1 - 9 + (3 * eta_c - 3) * omega * xi) .* beta.^2 ...
    + (3 * eta_1 - 3 * eta_2) * beta_1.^3 - 3 * eta_1 + 3 + (-3 * eta_c + 3) * omega.^3 * xi) .* k.^2 ...
    + (((12 * eta_s * rho_t * alpha - 12 * rho_c * (alpha - 1)) * n + 6 * eta_2) .* beta.^3 ...
    + (-6 * rho_t * kappa * (alpha + 1) * (eta_s - 1) * n + (9 * eta_1 - 9 * eta_2) * beta_1 - 9 * eta_1 + 9) .* beta.^2 ...
    + (-3 * eta_1 + 3 * eta_2) * beta_1.^3 + 3 * eta_1 - 3 + (3 * eta_c - 3) * omega.^3 * xi) .* k ...
    + ((-6 * eta_s * rho_t * alpha.^2 - 6 * rho_c * (alpha - 1).^2) * n - 2 * eta_2) .* beta.^3 ...
    + (6 * rho_t * alpha * kappa * (eta_s - 1) * n + (-3 * eta_1 + 3 * eta_2) * beta_1 + 3 * eta_1 - 3) .* beta.^2 ...
    + (eta_1 - eta_2) * beta_1.^3 - eta_1 + 1 + (-eta_c + 1) * omega.^3 * xi) .* E * b ...
    ./ (6 * (k - 1) .* beta.^2);


%epsilon_cr * E * b * h^2 * ((((-2 * xi * eta_c + 2 * eta_2) .* beta.^3 + ((3 * eta_1 - 3 * eta_2) .* beta_1 - 3 * eta_1 + 3 + (-3 * eta_c + 3) .* omega .* xi) .* beta.^2 + (-eta_1 + eta_2) .* beta_1.^3 + eta_1 - 1 + (eta_c - 1) .* omega.^3 .* xi) .* k.^3 + (((-6 * eta_s * rho_t - 6 * rho_c) .* n - 6 * eta_2) .* beta.^3 + (6 * rho_t * kappa * (eta_s - 1) .* n + (-9 * eta_1 + 9 * eta_2) .* beta_1 + 9 * eta_1 - 9 + (3 * eta_c - 3) .* omega .* xi) .* beta.^2 + (3 * eta_1 - 3 * eta_2) .* beta_1.^3 - 3 * eta_1 + 3 + (-3 * eta_c + 3) .* omega.^3 .* xi) .* k.^2 + (((12 * eta_s * rho_t * alpha - 12 * rho_c * (alpha - 1)) .* n + 6 * eta_2) .* beta.^3 + (-6 * rho_t * kappa * (alpha + 1) * (eta_s - 1) .* n + (9 * eta_1 - 9 * eta_2) .* beta_1 - 9 * eta_1 + 9) .* beta.^2 + (-3 * eta_1 + 3 * eta_2) .* beta_1.^3 + 3 * eta_1 - 3 + (3 * eta_c - 3) .* omega.^3 .* xi) .* k + ((-6 * eta_s * rho_t * alpha.^2 - 6 * rho_c * (alpha - 1).^2) .* n - 2 * eta_2) .* beta.^3 + (6 * rho_t * alpha * kappa * (eta_s - 1) .* n + (-3 * eta_1 + 3 * eta_2) .* beta_1 + 3 * eta_1 - 3) .* beta.^2 + (eta_1 - eta_2) .* beta_1.^3 - eta_1 + 1 + (-eta_c + 1) .* omega.^3 .* xi) ./ (6 * (k - 1) .* beta.^2));


phi= beta .* epsilon_cr ./ ((-k + 1) .* h);
defl = beta .* x .* epsilon_cr .* (-x + L) ./ (2 .* (k - 1) .* h);
defl_cant = -x2.^2 .* beta .* epsilon_cr ./ (2 .* (-1 + k) .* h);

ectop = k .* beta * epsilon_cr ./ (1 - k);
es_T = (-alpha + k) .* beta * epsilon_cr ./ (k - 1);

end