function [beta,k,M,phi,defl,defl_cant,ectop,es_T,es_C] = zone4222(beta,L,b,h,alpha,E,epsilon_cr,beta_1,beta_2,beta_3,eta_1,eta_2,eta_3,xi,omega,eta_c,n,kappa,eta_s,rho_c,rho_t)
x=L/2;%location to find deflection along the beam
x2 = L;

k = real(((-1 + beta_1) .* (beta_1 - 2 .* beta + 1) .* eta_1 - (beta_1 - beta_2) .* (beta_1 - 2 .* beta + beta_2) .* eta_2 + xi .* omega .* (beta + omega) .* eta_c - xi .* omega.^2 - beta .* omega .* xi - (beta_2 - beta).^2 .* eta_3 - n .* eta_s .* (rho_c + rho_t) .* beta.^2 + (-2 - kappa .* (rho_c - rho_t) .* (eta_s - 1) .* n) .* beta + sqrt(beta.^2 .* ((((beta - kappa) .* rho_t + rho_c .* (beta + kappa)) .* eta_s - (rho_c - rho_t) .* kappa).^2 .* n.^2 + ((((2 .* eta_c .* xi .* alpha - 2 .* eta_3 .* (alpha - 1)) .* beta.^2 + ((4 .* omega .* (eta_c - 1) .* alpha + (-2 .* kappa - 2 .* omega) .* eta_c + 2 .* omega) .* xi - 4 .* ((eta_1 - eta_2) .* beta_1 + (eta_2 - eta_3) .* beta_2 - eta_1 + 1) .* (alpha - 1)) .* beta + 2 .* omega .* (alpha .* omega - kappa - omega) .* (eta_c - 1) .* xi + 2 .* ((eta_1 - eta_2) .* beta_1.^2 + (eta_2 - eta_3) .* beta_2.^2 - eta_1 + 1) .* (alpha - 1)) .* rho_t - 2 .* ((eta_c .* (alpha - 1) .* xi - alpha .* eta_3) .* beta.^2 + ((2 .* omega .* (eta_c - 1) .* alpha + (-kappa - omega) .* eta_c + omega) .* xi - 2 .* ((eta_1 - eta_2) .* beta_1 + (eta_2 - eta_3) .* beta_2 - eta_1 + 1) .* alpha) .* beta + omega .* (alpha .* omega - kappa) .* (eta_c - 1) .* xi + ((eta_1 - eta_2) .* beta_1.^2 + (eta_2 - eta_3) .* beta_2.^2 - eta_1 + 1) .* alpha) .* rho_c) .* eta_s - 2 .* (rho_c - rho_t) .* (eta_c .* beta + omega .* (eta_c - 1)) .* kappa .* xi) .* n - (-eta_c .* eta_3 .* beta.^2 - 2 .* ((eta_1 - eta_2) .* beta_1 + (eta_2 - eta_3) .* beta_2 - eta_1 + 1) .* eta_c .* beta + omega.^2 .* (eta_c - 1) .* xi + ((eta_1 - eta_2) .* beta_1.^2 + (eta_2 - eta_3) .* beta_2.^2 - eta_1 + 1) .* eta_c) .* xi)) + 1) ./ ((-1 + beta_1) .* (beta_1 - 2 .* beta + 1) .* eta_1 - (beta_1 - beta_2) .* (beta_1 - 2 .* beta + beta_2) .* eta_2 + xi .* (beta + omega).^2 .* eta_c - xi .* omega.^2 - 2 .* beta .* omega .* xi - (beta_2 - beta).^2 .* eta_3 - 2 .* beta + 1));

M = h^2 * E * epsilon_cr * b * (((-2 * xi * eta_c + 2 * eta_3) .* beta.^3 + ((3 * eta_1 - 3 * eta_2) .* beta_1 + (3 * eta_2 - 3 * eta_3) .* beta_2 - 3 * eta_1 + 3 + (-3 * eta_c + 3) .* omega .* xi) .* beta.^2 + (-eta_1 + eta_2) .* beta_1.^3 + (-eta_2 + eta_3) .* beta_2.^3 + eta_1 - 1 + (eta_c - 1) .* omega.^3 .* xi) .* k.^3 + ((-6 * n * eta_s .* (rho_c + rho_t) - 6 * eta_3) .* beta.^3 + (-6 * kappa .* (rho_c - rho_t) .* (eta_s - 1) .* n + (-9 * eta_1 + 9 * eta_2) .* beta_1 + (-9 * eta_2 + 9 * eta_3) .* beta_2 + 9 * eta_1 - 9 + (3 * eta_c - 3) .* omega .* xi) .* beta.^2 + (3 * eta_1 - 3 * eta_2) .* beta_1.^3 + (3 * eta_2 - 3 * eta_3) .* beta_2.^3 - 3 * eta_1 + 3 + (-3 * eta_c + 3) .* omega.^3 .* xi) .* k.^2 + ((-12 * eta_s .* ((alpha - 1) .* rho_c - rho_t .* alpha) .* n + 6 * eta_3) .* beta.^3 + (-6 * (eta_s - 1) .* ((alpha - 2) .* rho_c + rho_t .* (alpha + 1)) .* kappa .* n + (9 * eta_1 - 9 * eta_2) .* beta_1 + (9 * eta_2 - 9 * eta_3) .* beta_2 - 9 * eta_1 + 9) .* beta.^2 + (-3 * eta_1 + 3 * eta_2) .* beta_1.^3 + (-3 * eta_2 + 3 * eta_3) .* beta_2.^3 + 3 * eta_1 - 3 + (3 * eta_c - 3) .* omega.^3 .* xi) .* k + (-6 * eta_s .* ((alpha - 1).^2 .* rho_c + rho_t .* alpha.^2) .* n - 2 * eta_3) .* beta.^3 + (6 * ((alpha - 1) .* rho_c + rho_t .* alpha) .* (eta_s - 1) .* kappa .* n + (-3 * eta_1 + 3 * eta_2) .* beta_1 + (-3 * eta_2 + 3 * eta_3) .* beta_2 + 3 * eta_1 - 3) .* beta.^2 + (eta_1 - eta_2) .* beta_1.^3 + (eta_2 - eta_3) .* beta_2.^3 - eta_1 + 1 + (-eta_c + 1) .* omega.^3 .* xi) ./ (6 * (k - 1) .* beta.^2);


phi= beta .* epsilon_cr ./ ((-k + 1) .* h);
defl = beta .* x .* epsilon_cr .* (-x + L) ./ (2 .* (k - 1) .* h);
defl_cant = -x2.^2 .* beta .* epsilon_cr ./ (2 .* (-1 + k) .* h);

es_C = -(k - 1 + alpha) .* beta * epsilon_cr ./ (k - 1);
ectop = k .* beta * epsilon_cr ./ (1 - k);
es_T = (-alpha + k) .* beta * epsilon_cr ./ (k - 1);

end